// icons.slint
// Centralized SVG asset paths. Import this global to use.
export global Icons {
    out property <image> copy-all: @image-url("../assets/copy_all.svg");
    out property <image> filter: @image-url("../assets/filter.svg");
    out property <image> favorite: @image-url("../assets/favorite.svg");
    out property <image> favorite-filled: @image-url("../assets/favorite_filled.svg");
    out property <image> folder: @image-url("../assets/folder.svg");
    out property <image> folder-open: @image-url("../assets/folder_open.svg");
    out property <image> image: @image-url("../assets/image.svg");
    out property <image> print: @image-url("../assets/print.svg");
    out property <image> side-navigation: @image-url("../assets/side_navigation.svg");
    out property <image> video-file: @image-url("../assets/video_file.svg");
    out property <image> flex-no-wrap: @image-url("../assets/flex_no_wrap.svg");
    out property <image> light-mode: @image-url("../assets/light_mode.svg");
    out property <image> dark-mode: @image-url("../assets/dark_mode.svg");
    out property <image> rotate-left: @image-url("../assets/rotate_left.svg");
    out property <image> rotate-right: @image-url("../assets/rotate_right.svg");
    out property <image> arrow-back-ios: @image-url("../assets/arrow_back_ios.svg");
    out property <image> arrow-forward-ios: @image-url("../assets/arrow_forward_ios.svg");
    out property <image> arrow-range: @image-url("../assets/arrow_range.svg");
    out property <image> swap-vert: @image-url("../assets/swap_vert.svg");
    out property <image> play-arrow: @image-url("../assets/play_arrow.svg");
    out property <image> square: @image-url("../assets/square.svg");
    out property <image> gradient: @image-url("../assets/gradient.svg");
    out property <image> square-unfilled: @image-url("../assets/square-unfilled.svg");
    out property <image> sort-alpha: @image-url("../assets/sort_by_alpha.svg");
    out property <image> sort-time: @image-url("../assets/nest_clock_farsight_analog.svg");
    out property <image> sort-size: @image-url("../assets/storage.svg");
    out property <image> sort-ascending: @image-url("../assets/arrow_upward.svg");
    out property <image> sort-descending: @image-url("../assets/arrow_downward.svg");
    out property <image> autocurve-3d: @image-url("../assets/3d_autocurve.svg");
    out property <image> hinton-plot: @image-url("../assets/hinton-plot.svg");
    out property <image> view-table: @image-url("../assets/view--table.svg");
}
